github: [your-username]
patreon: your-username
open_collective: your-project
ko_fi: your-username
tidelift: pypi/your-package
community_bridge: your-project
liberapay: your-username
issuehunt: your-username
otechie: your-username
custom: ['https://www.paypal.me/your-username'] 